filename = input("Enter a filename: ")  
infile = open(filename, "r")
print(infile.read())
infile.close()
infile1= open(filename, "w")
infile1.write("Something")
infile1.close()
infile2=open(filename,"a")
infile2.write("\nPython is interpreted\n")
infile2.close()