#leave application
print("To,")
print("The Chairman,")
print("SSUET,Karachi,")
print("13-Octuber-2022.")
print("\nSubject : Grant leave of seven days.")
print("\nRespected Sir/Ma'am,")
print("\t\tWith due respect and humble submission, I would like to inform you that I am the student of BSE-FALL-2022 Section B.",end=' ')
print("My name is Laiba Rafiq [Roll no.=64] of your University. I beg to say that I'm going to Islamabad with my parents on my",end=' ')
print("cousin's weddding,from 17/Oct/22  to 23/Oct/22. So I'm unable to attend my classes.") 
print("\t\tHence, I request you to kindly grant me leave for 1 week. I would be highly obliged and thanksful to you.")
print("\nThank You!")
print("\nYours Obediently,\t\t\t\t\t\t\t\t\t\t\t\tFaculty Signature,\n\t\t\t\t\t\t\t\t\t\t\t\t\t\tProfessor Rubina Zia:__________",end='')
print("\nLaiba Rafiq\t\t\t\t\t\t\t\t\t\t\t\t\tDr.M.Rashid Khan:__________ \nRoll no. 64\t\t\t\t\t\t\t\t\t\t\t\t\tDr.Ingila Rahim:",end='')
print("__________ \nMy Signature:__________\t\t\t\t\t\t\t\t\t\t\t\tEngr.Muhammad Saleem:__________ \n\t\t\t\t\t\t\t\t\t\t\t\t\t\tPro",end='')
print("fessor Hafsa Nizami:________\nChairman's Signature:_____________\t\t\t\t\t\t\t\t\t\tEngr.Tauseef Mubeen:__________ ")
print("\t\t\t\t\t\t\t\t\t\t\t\t\t\tEngr.Ali Yousuf Khan:__________ ")