#bio-data
print("\t\t\t\t\t\t\t\"LAIBA RAFIQ\"")
print("\t\t\t\t\t\t     ~Software Engineer~")
print("\t\t\t\t\t-Address:123 Gulshan Street, Karachi, Pakistan")
print("\t\t\t\t\t-Email:laibarafique2005@gmail.com ,-Phone no:021-37089600")
print("\n\n\t\t\t\t\t\t   \"-PROFESSIONAL SUMMARY-\"\nExperienced software engineer with a passion of developing innovative programs",end=' ')
print("that expedite the efficiency and effectiveness of organizational success. Well-versed in technology and writing code to",end=' ')
print("create systems that are reliable and user-friendly. Skilled leader who has the proven ability to motivate, educate, and",end=' ')
print("manage  a team of professionals to build software programs and effectively track changes. Confident communicator,strategic",end=' ')
print(" thinker, and innovative creator to develop software that is customised to meet a company's organizational needs and",end=' ')
print("highlight their core competencies and further their success.")
print("\n\t\t\t\t\t\t       \"-EDUCATION-\"\n\n-Matriculation:\nPassed SSC from THE EDUCATORS Gulshan Campus III {Karachi Board}-2020")
print("\n-Intermediate:\nPassed HSC from SREE-III MAJEED {Karachi Board}-2022")
print("\n-Bachelors Of Software Engineering:\nPassed BSE from SSUET Karachi-2026")
print("\n-Masters In Software Engineering:\nIn Progress from FAST University Karachi-2026 to 2028")
print("\n\t\t\t\t\t\t     \"-WORK EXPERIENCE-\"\n\n-Software Engineer:\t\"TimeXperts\" {2026-Current}")
print("-Participated in creating scalable systems for 3 primary departments including human resources, marketing and supply chain.")
print("-Ran monthly unit tests to determine software effectiveness and mend broken links or glitches in the systems.")
print("-Gave quarterly reports to executive management regarding current developments and tracked changes in existing software.")
print("\n-Software Engineer Internship:\t\"10Pearls\" {2024-2025}")
print("-Research best practices to share with fellow software team members.\n-Helped write code for a website update using HTML tools.")
print("-Presented to management an end-of-term demonstration on valuable software developments that were in the works.")
print("\n\t\t\t\t\t\t      \"-KEY SKILLS-\"\n\n-Well-versed in software tools including HTML,JavaScript,CSS,Pyhton,Backbone and",end=' ')
print("JQuery among others.")
print("-Experienced at designing unit tests to check software programs,backend services and user interface.")
print("-Confident problem solving abilities with creative solutions.\n-Strong communication skills and ability to carefully listen",end=' ')
print("to user feedback for modifications.\n-Web-based software engineering.\n-Database programming.\n-Software applications.\n-Code reviews")
print("\n\t\t\t\t\t\t       \"-PERSONAL-\"\n-Nationality:Pakistani\n-Marital Status:Single\n-Birthday:22nd March 2004\n-Height:5'5")
print("-Language:Urdu and English")
print("\n\t\t\t\t\t\t       \"-REFERENCE-\"\n-Available on request")